### ISSUE TITLE
Awesome project

### ISSUE THREAD

**Issue by Nukesor** [ema/pets#4]
Hey!

Originally I wanted to send you an email, but I couldn't find a way of contacting you except twitter (which I don't have/use).
Hence, the dirty message in ticket approach.

The thing is, that I'm currently in the design phase of a tool that has the exact same use-case.

My plan was to meet up with a good friend in a few days to verify the design. Imagine my astonishment when he sent me your project this morning :D.
At this point, I want to say that I really like the name of the project.

What was most surprising is that you went with a few core design decisions I was keen on using, but really wasn't sure about:
- In file configuration
- The one directory per system rule
- No inter-file dependencies
I guess those cannot be too much of a bad idea then.

From here on, the design starts to differs quite a bit though.
I planned to have the configuration for various different systems in the same directory, including a way to have a "base" configuration that's shared for all systems.
My plan was also to go with templating (at least for those "base" files), even though I'm not yet sure how to inject variables in a nice way.

From what I understand, your plan is to keep this project rather minimalistic (which I respect a lot) and stick to your design decisions.

If that's the case, I'll probably continue building my project as planned :).
I just wanted to tell you aren't the only one that's annoyed by the current PC configuration situation :D.

Best regards,

Arne Beer

**Comment by ema** [comment]
> The thing is, that I'm currently in the design phase of a tool that has the exact same use-case.

Very nice.
 
> My plan was to meet up with a good friend in a few days to verify the design. Imagine my astonishment when he sent me your project this morning :D. At this point, I want to say that I really like the name of the project.

Thanks!

> I planned to have the configuration for various different systems in the same directory, including a way to have a "base" configuration that's shared for all systems. My plan was also to go with templating (at least for those "base" files), even though I'm not yet sure how to inject variables in a nice way.
> 
> From what I understand, your plan is to keep this project rather minimalistic (which I respect a lot) and stick to your design decisions.

Yup.
 
> If that's the case, I'll probably continue building my project as planned :). I just wanted to tell you aren't the only one that's annoyed by the current PC configuration situation :D.

Go ahead! From what I understand your project takes a slightly different angle, including support for configuration reuse which I explicitly decided to avoid. Plus, no songwriter ever dropped the idea of writing a love song given that there was another one already. :-)

Have fun and send me a link to your project once it starts taking shape at ema [at] linux.it.
